[tox]
# disabled pip8 + cover to pass CI
#envlist = py310,py311,p312,pep8,cover
envlist = py310,py311,p312
minversion = 1.6
# install logshipper into tox virtualenv to run pytest.
skipsdist = False

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[testenv]
usedevelop = True
deps =
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
commands =
    pip list
    pytest logshipper/test


[testenv:cover]
setenv = VIRTUAL_ENV={envdir}
         NOSE_WITH_COVERAGE=1
         NOSE_COVER_BRANCHES=1
         NOSE_COVER_PACKAGE=logshipper
         NOSE_COVER_HTML=1
         NOSE_COVER_HTML_DIR={toxinidir}/cover

[testenv:pep8]
commands =
  flake8 logshipper setup.py

[testenv:venv]
commands = {posargs}

[flake8]
exclude = .venv,.tox,dist,*egg
show-source = True
ignore = H803,H802

[testenv:docs]
basepython=python
deps =
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
  sphinx
commands=invoke build_docs
